services:
  stockmode.webapi:
    image: ${DOCKER_REGISTRY-}stockmodewebapi
    build:
      context: .
      dockerfile: src/StockMode.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=mailrabbit
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - app_network

  stockmode.mailworker:
    image: ${DOCKER_REGISTRY-}stockmodemailsender
    build:
      context: .
      dockerfile: src/StockMode.EmailWorker/Dockerfile
    environment:
      - RABBITMQ_HOST=mailrabbit
    depends_on:
      - rabbitmq
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: igorsantanamedeiros17@gmail.com
      PGADMIN_DEFAULT_PASSWORD: StockMode123@@
    depends_on:
      - postgres
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: mailrabbit
    hostname: mailrabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

networks:
  app_network:
    driver: bridge


