apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-autoscale
  namespace: stockmode
  labels:
    app: stockmode-frontend
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stockmode-frontend
  targetCPUUtilizationPercentage: 50