apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stockmode-idp-keys-pvc
  namespace: stockmode
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi  
  resources:
    requests:
      storage: 1Gi  
