apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stockmode-ingress
  namespace: stockmode
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: stockmode-app.westus2.cloudapp.azure.com
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: stockmode-api-service
            port:
              number: 80
      - path: /idp(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: stockmode-idp-service
            port:
              number: 5001
      - path: /()(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: stockmode-frontend-service
            port:
              number: 80